### ISSUE TITLE
Markdown to ePub Edgecase Document List

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#1027]
- [x] #1050
- [x] Internal links that are part of the same collection need to be removed entirely (`![Some link](/posts/ffg-other)` -> `Some link`)
- [x] #1051
- [x] ~~`<iframe>` with `uu-code` links need to be removed entirely~~
  * Because this content can be wrapped in `no-epub` comments, these can be handled the same as other iframes.
- [x] External links need to generate reference links:
  * [x] `<a>` and `<iframe>` elements need to be collected and numbered for each chapter of each book.
  * [x] `<a>` elements should have superscript for their link number
      - e.g. "[Here is a link.](https://example.com)<sup>[37]</sup>"
  * [x] `<iframe>` elements should be replaced with a link based on the embed title
      - e.g. "[React What is a Directive? - StackBlitz](https://example.com)<sup>[38]</sup>"
  * [x] A "References" chapter should be added at the end of each book containing a list of all referenced links
      - This should be split by chapter - e.g. "Chapter 8, Element Reference" -> Link 37 -> https:\/\/example.com
      - The link numbers are still unique - so Chapter 8 might contain Links 32-39, and Chapter 9 might have Links 40-42

**Comment by fennifith** [comment]
> Internal links that are part of the same collection need to be removed entirely

It looks like [internal links](https://electricbookworks.github.io/ebw-training/making-ebooks/text/4-links.html) are possible within an epub - likewise for supporting anchors/heading links. Would this be something we want to implement instead of removing them entirely?

(this would require mapping each chapter link to the `filename` that it goes into - which can be passed into [html-to-epub](https://www.npmjs.com/package/@lesjoursfr/html-to-epub))
