### ISSUE TITLE
[Website Bug]: Large chunks of empty space reserved for content

### ISSUE THREAD

**Issue by MateuszWasik** [unicorn-utterances/unicorn-utterances#1053]
### Description

I came across a large section of blank space between one chapter and the next. After looking in the code, I noticed that this blank space is reserved for content that is currently hidden. It might be worth looking into this and see if we can try to allocate the space more dynamically.

<img width="1005" alt="image" src="https://github.com/unicorn-utterances/unicorn-utterances/assets/26119440/8a599b29-c3ab-4413-951f-ce541e783623">

### Minimal Reproduction

- Chapter 4 - Side Effects
- Go to Challenge section

**Comment by crutchcorn** [comment]
This is intentional behavior to prevent page shift (CC @fennifith per prior convos)

I think we should/can change it, but there's an argument to be had for keeping it to make switching tabs more seemless

**Comment by fennifith** [comment]
Yeah - that amount of space is large enough that preventing page shift is no longer useful. There's a piece of logic (in the rehype plugins) that's *supposed* to turn off the space-preserving for tabs with any significant amount of content in them, so that it only affects small tab groups - but this is based on a very rough estimate. Based on this, it probably isn't accounting for the images.

We also had a discussion about making the tab container extend to the full expanded height in these cases, so that the gap looks more intentional (when it's meant to be there).

**Comment by MateuszWasik** [comment]
@fennifith @crutchcorn thanks. If you feel like we need to mark that task as or `enhancement` please do so. Otherwise we can close it.
