### ISSUE TITLE
About Us Sponsor Logo

### ISSUE THREAD

**Issue by friedelinehustenkraehe** [unicorn-utterances/unicorn-utterances#274]
When I click on the logo of a [sponsor](https://unicorn-utterances.com/about#Sponsors) it opens a new tab with its website but when I go back to the Unicorn Utterances page I just see the sponsor's logo in maximum size. Is that the desired behaviour? Because I would find it more comfortable if the page would stay as is and just open the sponsor's website in a new tab. Please let me know if you need more information in case you cannot retrace my issue.
By the way, thanks for the amazing posts on the blog. 👍

**Comment by crutchcorn** [comment]
You know, I think I recognized this as an issue some time ago in the middle of the sponsors section revamp, then promptly forgot about it because I have the attention span of a house fly 😅

What's happening here, for context, is that we have a plugin enabled called `gatsby-remark-images-medium-zoom`. But for these items we ALSO have `<a` tags wrapping those images. I aught to add logic to disable that, as that's far from ideal behavior 

Thanks for reporting this! 

Likewise, thanks for the comment about the content! 😊 If you happen to have a Discord, we actually have a community there that's fairly active. We chat about coding stuff of all kinds 

https://discord.gg/FMcvc6T

**Comment by crutchcorn** [comment]
Closing - this issue has now been solved on production! :)
