### ISSUE TITLE
Back button should take user to previous page instead of homepage in some situations

### ISSUE THREAD

**Issue by adueppen** [unicorn-utterances/unicorn-utterances#45]
Currently the back button is hardcoded to route the user back to the homepage which definitely makes sense for things like blog posts, but when going from homepage --> about page/blog post --> unicorn page, the back button there should return the user to the previous page they were on instead of the homepage.

**Comment by crutchcorn** [comment]
I admittedly thought we had a story for this. Unfortunately, that's a bit complicated. 

We'd need this to be merged first: 
https://github.com/reach/router/pull/197

Otherwise, trying to add `location.back` would hard reload the last page which would break a lot of transition functionality/etc

**Comment by crutchcorn** [comment]
I found an issue (now that reach/router#197 was merged) where `navigation` from `gatsby` doesn't allow -1 to be passed (the back command) due to it's query parsing. I am trying to talk to the Gatsby team about opening a PR myself to fix this issue, but have gotten stuck on a technical issue and am awaiting a reply from them. More as this develops

**Comment by crutchcorn** [comment]
https://github.com/gatsbyjs/gatsby/pull/19044 we're now waiting on this
