### ISSUE TITLE
[UwU] Table of Contents colors need fixing

### ISSUE THREAD

**Issue by PrattiDev** [unicorn-utterances/unicorn-utterances#572]
The dot/arrow in the ToC component is set to `primary40` at all times. The correct token for it is `primary.default`.

![ToC comparison](https://github.com/unicorn-utterances/unicorn-utterances/assets/17130024/4ff41ae4-ed4b-45e2-a9ac-84fc6e9a4257)
---

The ToC divider/inset indicator is currently being mapped to static hex values as opposed to our tokens.
```
--toc_divider_color: #cddbe7;
```
When it should be
```
--toc_divider_color: var(--background_disabled);
```
---
### To-Do

- [x] Apply variable to ToC sub-item dot.
- [x] Apply correct variable to ToC inset divider.
---

**Comment by crutchcorn** [comment]
Inset divider _is_ set to the correct color. That hex value is explained in the code by being the hardcoded alpha `disabled` applied to the non-alpha `primary`.

This is because otherwise we end up with striping:

<img width="287" alt="image" src="https://github.com/unicorn-utterances/unicorn-utterances/assets/9100169/83b152e1-5ecc-49a2-acf2-8a8f8edf6481">

As the way we had to implement the lines was to have them overlap slightly
